import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGalleryEmbed from '../../../../../shared/markdown/plugins/remarkGalleryEmbed';
import type { Node } from 'unist';

// --- Types ---

interface GalleryEmbedNode extends Node {
  type: 'galleryEmbed';
  data: {
    hName: string;
    hProperties: {
      className: string;
      'data-album-id': string;
      'data-layout': string;
      'data-limit': string;
      'data-show-description': string;
      'data-show-title': string;
    };
  };
}

// --- Helpers ---

function findGalleryEmbedNodes(node: Node): GalleryEmbedNode[] {
  const results: GalleryEmbedNode[] = [];
  if (node.type === 'galleryEmbed') {
    results.push(node as GalleryEmbedNode);
  }
  if ('children' in node && Array.isArray((node as { children?: unknown[] }).children)) {
    for (const child of (node as { children: Node[] }).children) {
      results.push(...findGalleryEmbedNodes(child));
    }
  }
  return results;
}

function parseDirective(markdown: string): Node {
  const processor = unified().use(remarkParse).use(remarkGalleryEmbed);
  return processor.runSync(processor.parse(markdown));
}

/**
 * Build a directive string in the same format as AlbumPickerDialog.handleConfirm:
 * ::gallery[{slug}]{layout={layout} limit={limit} showDescription={showDescription} showTitle={showTitle}}
 */
function buildDirective(
  slug: string,
  layout: string,
  limit: number,
  showDescription: boolean,
  showTitle: boolean,
): string {
  return `::gallery[${slug}]{layout=${layout} limit=${limit} showDescription=${showDescription} showTitle=${showTitle}}`;
}

// --- Generators ---

const validSlug = fc.stringMatching(/^[a-zA-Z0-9][a-zA-Z0-9-]{0,19}$/);
const validLayout = fc.constantFrom('grid', 'carousel', 'masonry');
const validLimit = fc.integer({ min: 0, max: 100 });
const validBool = fc.boolean();

// --- Property Tests ---

describe('AlbumPickerDialog — directive generation property tests', () => {
  /**
   * Property 6: Directive Generation Correctness
   *
   * For any album slug (matching ^[a-zA-Z0-9-]+$) and any valid EmbedConfig combination,
   * the directive string generated by the Album Picker Dialog SHALL be parseable back
   * through the remarkGalleryEmbed plugin to produce a galleryEmbed AST node with the
   * same album ID and equivalent configuration values.
   *
   * **Validates: Requirements 3.6**
   */
  describe('Property 6: Directive Generation Correctness', () => {
    it('generated directives from AlbumPickerDialog are parseable back through remarkGalleryEmbed producing correct AST nodes', () => {
      fc.assert(
        fc.property(
          validSlug,
          validLayout,
          validLimit,
          validBool,
          validBool,
          (slug, layout, limit, showDescription, showTitle) => {
            // Build directive in the same format as AlbumPickerDialog
            const directive = buildDirective(slug, layout, limit, showDescription, showTitle);

            // Parse through remarkGalleryEmbed
            const tree = parseDirective(directive);
            const nodes = findGalleryEmbedNodes(tree);

            // Should produce exactly one galleryEmbed AST node
            expect(nodes).toHaveLength(1);

            const props = nodes[0].data.hProperties;

            // Album ID matches slug
            expect(props['data-album-id']).toBe(slug);

            // Layout matches
            expect(props['data-layout']).toBe(layout);

            // Limit: plugin stores limit only if parsed > 0, otherwise keeps default "0"
            const expectedLimit = limit > 0 ? String(limit) : '0';
            expect(props['data-limit']).toBe(expectedLimit);

            // showDescription matches
            expect(props['data-show-description']).toBe(String(showDescription));

            // showTitle matches
            expect(props['data-show-title']).toBe(String(showTitle));
          },
        ),
        { numRuns: 100 },
      );
    });
  });
});
